services:
  - type: web
    name: LuxePrestige
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: python manage.py migrate && gunicorn Ecommerce.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: luxeprestige.onrender.com,.onrender.com,127.0.0.1,localhost
      - key: DATABASE_URL
        fromDatabase:
          name: luxeprestige_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ENVIRONMENT
        value: production
      - key: CSRF_TRUSTED_ORIGINS
        value: https://luxeprestige.onrender.com,https://*.onrender.com

databases:
  - name: luxeprestige_db
    databaseName: luxeprestige_db
    user: luxeprestige_user
    plan: free
